name: Test Windows build
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    env:
      WORKING_DIRECTORY: Example
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Check node modules cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --pure-lockfile

      - name: Install Example node modules
        working-directory: ${{ env.WORKING_DIRECTORY }}
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --pure-lockfile

      - name: Build x64 release
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: powershell
        run: npx react-native run-windows --root Example --arch x64 --release --no-packager --no-deploy --logging
